import { createT } from "../../../renderer/src/i18n";

const es = {
  "nav": "Productos",
  "title": "Productos",
  "new": "Nuevo producto",
  "search": "Buscar por nombre o categoría",
  "showInactive": "Ver también los retirados",
  "empty.title": "Todavía no hay productos",
  "empty.body": "Crea el primero con su precio. Si se vende en varias tallas, colores o presentaciones, podrás poner las existencias de cada una.",
  "none.title": "Ningún producto coincide",
  "none.body": "Prueba con otra palabra, quita algún filtro o revisa si está retirado de la venta.",
  "limit": "Se muestran los primeros {count}. Usa el buscador para encontrar los demás.",
  "col.product": "Producto",
  "col.price": "Precio",
  "col.pieces": "Variantes",
  "col.stock": "Existencias",
  "pieces.single": "Pieza única",
  "pieces.none": "—",
  "price.from": "desde {price}",
  "price.open": "Al cobrar",
  "review": "Revisar existencias",
  "low": "Por reponer",
  "inactive": "Retirado",
  "service": "Servicio",
  "stock.action": "Existencias de {name}",

  "filter.kind": "Qué ver",
  "filter.kind.all": "Todo",
  "filter.kind.products": "Productos",
  "filter.kind.services": "Servicios",
  "filter.category": "Categoría",
  "filter.category.all": "Todas las categorías",

  "stat.products": "Productos en venta",
  "stat.services.one": "y 1 servicio",
  "stat.services": "y {count} servicios",
  "stat.pieces": "Piezas en existencia",
  "stat.value": "Valor a precio de venta",
  "stat.cost": "Costó {amount}",
  "stat.cost.partial": "Costó {amount} · {count} sin costo anotado",
  "stat.low": "Por reponer",
  "stat.low.note": "Con piezas en el mínimo",
  "stat.negative": "Por revisar",
  "stat.negative.note": "Se vendió sin tener",
  "stat.filter.on": "Mostrando solo estos. Toca para ver todos.",

  "editor.new": "Nuevo producto",
  "editor.new.service": "Nuevo servicio",
  "editor.edit": "Editar producto",
  "editor.edit.service": "Editar servicio",
  "kind": "Qué es",
  "kind.product": "Producto",
  "kind.service": "Servicio",
  "kind.service.hint": "Un servicio (un corte, una reparación) no lleva existencias.",
  "name": "Nombre",
  "name.placeholder": "Ej.: Zapato deportivo",
  "name.placeholder.service": "Ej.: Corte de cabello",
  "name.required": "Escribe el nombre.",
  "category": "Categoría",
  "category.placeholder": "Elige o escribe una",
  "category.hint.template": "Se vende por {options}: toca los valores que tengas.",
  "price": "Precio de venta",
  "price.invalid": "Escribe el precio como un número, por ejemplo 45 o 45,50.",
  "openPrice": "El precio se escribe al cobrar",
  "openPrice.hint": "Para trabajos a medida: cada vez que lo vendas, Ventamas te pedirá el precio.",
  "cost": "Costo (opcional)",
  "cost.hint": "Lo que te costó. Sirve para saber cuánto ganas.",
  "cost.invalid": "Escribe el costo como un número, o déjalo vacío.",
  "margin": "Ganas {profit} en cada venta · margen del {margin} %",
  "margin.loss": "Lo vendes por debajo del costo: pierdes {loss} en cada venta.",
  "tax": "Impuesto",
  "minStock": "Avisar cuando queden",
  "minStock.suffix": "o menos de una pieza",
  "minStock.hint": "Déjalo vacío para no avisar. Con 0, avisa cuando se agote.",
  "minStock.invalid": "Escribe un número entero, o déjalo vacío.",

  "variants.title": "Variantes",
  "variants.title.service": "Modalidades",
  "variants.toggle": "Se vende en varias tallas, colores o presentaciones",
  "variants.toggle.service": "Tiene modalidades con distinto precio",
  "variants.hint": "Cada variante tiene su nombre (Talla, Capacidad, Sabor…) y sus valores, separados por comas. Puedes usar una o dos.",
  "variants.hint.service": "Por ejemplo: Para (Caballero, Dama, Niño) o Vehículo (Moto, Carro). Separa los valores con comas.",
  "option1": "Primera variante",
  "option2": "Segunda variante (opcional)",
  "option.placeholder1": "Ej.: Talla",
  "option.placeholder2": "Ej.: Color",
  "option.required": "Ponle nombre a esta variante.",
  "option.same": "Las dos variantes no pueden llamarse igual.",
  "values1": "Valores de la primera variante",
  "values2": "Valores de la segunda variante",
  "values.placeholder": "Separados por comas",
  "values.suggested": "Habituales:",
  "ownPrices": "Cada una tiene su precio",

  "pieces.title": "Existencias y códigos",
  "pieces.title.service": "Códigos y precios",
  "pieces.hint": "Escribe cuántas piezas hay de cada una. El código es el de barras o uno propio, y es opcional.",
  "pieces.hint.service": "El código es opcional: sirve para encontrar el servicio escribiéndolo o escaneándolo.",
  "col.code": "Código",
  "col.qty": "Existencias",
  "col.piecePrice": "Precio",
  "piecePrice.invalid": "Algún precio no es un número. Corrígelo o déjalo vacío para usar el del producto.",
  "stock.invalid": "Las existencias son un número entero.",
  "codes.generate": "Generar los códigos que faltan",
  "codes.hint": "Códigos propios para imprimir etiquetas. Son solo para tu tienda.",
  "remove": "Quitar {piece}",
  "restore.one": "Restaurar la combinación quitada",
  "restore": "Restaurar las {count} combinaciones quitadas",
  "save": "Guardar",
  "cancel": "Cancelar",
  "retire": "Retirar de la venta",
  "reactivate": "Volver a vender",
  "retired.note": "Está retirado: no aparece al vender.",

  "moves.title": "Existencias · {name}",
  "moves.tab.move": "Registrar movimiento",
  "moves.tab.history": "Historial",
  "moves.reason": "Qué pasó",
  "reason.entrada": "Llegó mercancía",
  "reason.conteo": "Conté lo que hay",
  "reason.dano": "Se dañó",
  "reason.perdida": "Se perdió",
  "reason.uso": "Uso propio",
  "reason.inicial": "Existencia inicial",
  "reason.ajuste": "Ajuste",
  "reason.venta": "Venta",
  "reason.devolucion": "Devolución",
  "reason.anulacion": "Anulación",
  "moves.piece": "Pieza",
  "moves.piece.stock": "{piece} (hay {count})",
  "moves.qty.entrada": "Piezas que llegaron",
  "moves.qty.conteo": "Piezas que hay ahora",
  "moves.qty.out": "Piezas que salen",
  "moves.qty.invalid": "Escribe una cantidad entera mayor que cero.",
  "moves.qty.invalid.count": "Escribe cuántas hay: un número entero, cero o más.",
  "moves.cost": "Costo de cada pieza (opcional)",
  "moves.cost.hint": "Actualiza el costo del producto promediando con lo que ya había.",
  "moves.note": "Nota (opcional)",
  "moves.note.placeholder": "Ej.: Pedido de octubre",
  "moves.submit": "Registrar",
  "moves.done": "Registrado. Ahora hay {count} de {piece}.",
  "moves.done.single": "Registrado. Ahora hay {count}.",
  "moves.same": "Ya había {count}: no hizo falta registrar nada.",
  "moves.close": "Cerrar",
  "moves.empty": "Todavía no hay movimientos.",
  "moves.col.date": "Fecha",
  "moves.col.piece": "Pieza",
  "moves.col.reason": "Motivo",
  "moves.col.qty": "Cantidad",
  "moves.col.balance": "Quedaron",
  "moves.col.note": "Nota",

  "cats.title": "Tipo de comercio y categorías",
  "cats.label": "Categorías",
  "cats.hint":
    "Elige lo que vende tu tienda y Ventamas carga sus categorías, cada una con las variantes que suelen tener sus productos. Puedes cargar varios y cambiar lo que quieras después.",
  "cats.rubros": "Tipos de comercio",
  "cats.rubro.count": "{count} categorías",
  "cats.rubro.load": "Cargar",
  "cats.rubro.load.label": "Cargar las categorías de {name}",
  "cats.rubro.loaded": "Cargado",
  "cats.rubro.added": "Se añadieron {count} categorías de {name}.",
  "cats.rubro.added.none": "Ya tenías todas las categorías de {name}.",
  "cats.rubro.more": "Ver los {count} tipos de comercio",
  "cats.rubro.less": "Ver menos",
  "cats.list": "Tus categorías",
  "cats.list.empty": "Todavía no hay categorías. Carga un tipo de comercio o crea la primera.",
  "cats.new": "Nueva categoría",
  "cats.showHidden": "Ver también las ocultas",
  "cats.col.name": "Categoría",
  "cats.col.variants": "Variantes",
  "cats.col.products": "Productos",
  "cats.variants.none": "Sin variantes",
  "cats.hidden": "Oculta",
  "cats.edit": "Editar",
  "cats.editor.new": "Nueva categoría",
  "cats.editor.edit": "Editar categoría",
  "cats.name": "Nombre",
  "cats.name.required": "Escribe el nombre de la categoría.",
  "cats.kind": "Es de",
  "cats.kind.product": "Productos",
  "cats.kind.service": "Servicios",
  "cats.option1": "Primera variante",
  "cats.option2": "Segunda variante",
  "cats.values": "Valores habituales",
  "cats.values.hint": "Separados por comas. Se ofrecen con un toque al crear un producto de esta categoría.",
  "cats.active": "Ocultar esta categoría",
  "cats.active.hint": "No se ofrece al crear productos. Los que ya la tienen la conservan.",

  "welcome.title": "¿Qué vende tu tienda?",
  "welcome.body": "Elige uno o varios. Ventamas carga sus categorías y las variantes de cada una, para que no empieces de cero. Podrás cambiarlas después.",
  "welcome.none": "Si no encuentras el tuyo, sigue sin elegir: podrás crear tus propias categorías.",
} as const;

export const t = createT(es);
