import { createT } from "../../../renderer/src/i18n";

const es = {
  "nav": "Productos",
  "title": "Productos",
  "new": "Nuevo producto",
  "search": "Buscar por nombre o categoría",
  "showInactive": "Ver también los retirados",
  "empty.title": "Todavía no hay productos",
  "empty.body": "Crea el primero con su precio y, si se vende por tallas o colores, con las existencias de cada uno.",
  "none.title": "Ningún producto coincide",
  "none.body": "Prueba con otra palabra o revisa si está retirado de la venta.",
  "limit": "Se muestran los primeros {count}. Usa el buscador para encontrar los demás.",
  "col.product": "Producto",
  "col.price": "Precio",
  "col.pieces": "Tallas y colores",
  "col.stock": "Existencias",
  "pieces.single": "Pieza única",
  "review": "Revisar existencias",
  "inactive": "Retirado",

  "editor.new": "Nuevo producto",
  "editor.edit": "Editar producto",
  "name": "Nombre",
  "name.placeholder": "Ej.: Zapato deportivo",
  "name.required": "Escribe el nombre del producto.",
  "category": "Categoría",
  "category.placeholder": "Ej.: Calzado",
  "price": "Precio de venta",
  "price.invalid": "Escribe el precio como un número, por ejemplo 45 o 45,50.",
  "cost": "Costo (opcional)",
  "cost.hint": "Lo que te costó. Sirve para saber cuánto ganas.",
  "cost.invalid": "Escribe el costo como un número, o déjalo vacío.",
  "sizes": "Tallas",
  "sizes.placeholder": "Ej.: 36, 37, 38",
  "colors": "Colores",
  "colors.placeholder": "Ej.: Negro, Blanco",
  "variants.hint":
    "Separa con comas; para medias tallas usa punto (37.5). Deja ambos vacíos si el producto no se vende por tallas ni colores.",
  "pieces.title": "Existencias y códigos",
  "pieces.hint": "Escribe cuántas piezas hay de cada una. El código es el de barras o uno propio, y es opcional.",
  "col.size": "Talla",
  "col.color": "Color",
  "col.code": "Código",
  "col.qty": "Existencias",
  "stock.invalid": "Las existencias son un número entero.",
  "remove": "Quitar {piece}",
  "restore": "Restaurar las {count} combinaciones quitadas",
  "save": "Guardar",
  "cancel": "Cancelar",
  "retire": "Retirar de la venta",
  "reactivate": "Volver a vender",
  "retired.note": "Este producto está retirado: no aparece al vender.",
} as const;

export const t = createT(es);
