import { createT } from "../../../renderer/src/i18n";

const es = {
  "nav.settings": "Ajustes",
  "settings.title": "Ajustes",
  "settings.tabs": "Secciones de Ajustes",
  "settings.tab.store": "Tienda",
  "settings.tab.about": "Acerca de",
  "settings.store.title": "Tu tienda",
  "settings.store.hint": "Estos datos encabezan los recibos. Solo el nombre es necesario; lo demás, si quieres que salga impreso.",
  "settings.store.name": "Nombre de la tienda",
  "settings.store.name.hint": "Aparece en la barra lateral y en los recibos. Máximo {max} caracteres.",
  "settings.store.name.placeholder": "Ej.: Calzados Altamira",
  "settings.store.address": "Dirección (opcional)",
  "settings.store.address.placeholder": "Ej.: Av. Principal de Chacao, local 4, Caracas",
  "settings.store.phone": "Teléfono (opcional)",
  "settings.store.phone.placeholder": "Ej.: 0212 555 00 11",
  "settings.store.taxId": "RIF (opcional)",
  "settings.store.taxId.placeholder": "J-12345678-9",
  "settings.store.taxId.check": "El último dígito no coincide con ese RIF. Revísalo.",
  "settings.store.legalName": "Razón social (opcional)",
  "settings.store.legalName.hint": "El nombre legal, si es distinto del nombre de la tienda.",
  "settings.save": "Guardar",
  "settings.saved": "Guardado",
  "settings.theme.title": "Color",
  "settings.theme.hint": "Elige el color que más se parezca a tu tienda. Se aplica al instante.",
  "settings.theme.dark": "oscuro",
  "settings.currency.title": "Moneda de los precios",
  "settings.currency.hint": "Se eligió al configurar la tienda y no se cambia: los precios guardados están en ella.",
  "settings.about.title": "Acerca de",
  "settings.about.version": "Versión",
  "settings.about.license": "Licencia",
  "settings.about.license.value": "AGPL-3.0 · software libre y de código abierto",
  "settings.about.data": "Tus datos se guardan en",
  "settings.about.openData": "Abrir carpeta",

  "welcome.hello": "Te damos la bienvenida a Ventamas",
  "welcome.lead": "Tres preguntas y empiezas a vender. Todo se puede cambiar después en Ajustes.",
  "welcome.step": "Paso {step} de {total}",
  "welcome.name.title": "¿Cómo se llama tu tienda?",
  "welcome.name.body": "Sale en la pantalla y encabeza tus recibos.",
  "welcome.name.skip": "Si aún no lo decides, déjalo vacío y ponlo después.",
  "welcome.money.title": "¿En qué moneda están tus precios?",
  "welcome.money.body": "Es la moneda en la que escribes cada precio. Cobras en cualquiera: Ventamas convierte con la tasa del día.",
  "welcome.money.label": "Moneda de los precios",
  "welcome.money.USD": "Dólares",
  "welcome.money.USD.hint": "Lo habitual: el precio no cambia cuando cambia la tasa.",
  "welcome.money.VES": "Bolívares",
  "welcome.money.VES.hint": "Tendrás que actualizar los precios cuando suba la tasa.",
  "welcome.money.EUR": "Euros",
  "welcome.money.EUR.hint": "Si compras y marcas tu mercancía en euros.",
  "welcome.money.fixed": "Esta es la única elección que no se puede cambiar después.",
  "welcome.theme.title": "Elige un color",
  "welcome.back": "Atrás",
  "welcome.next": "Continuar",
  "welcome.finish": "Empezar a vender",
  "welcome.skip": "Omitir y configurar después",
} as const;

export const t = createT(es);
