import { createT } from "../../../renderer/src/i18n";

const es = {
  "nav": "Clientes",
  "title": "Clientes",
  "new": "Nuevo cliente",
  "search": "Buscar por nombre, cédula o teléfono",
  "showInactive": "Ver también los archivados",
  "empty.title": "Todavía no hay clientes",
  "empty.body": "Regístralos aquí o al vender. Con el nombre basta; la cédula o el RIF hacen falta para facturar.",
  "none.title": "Ningún cliente coincide",
  "none.body": "Prueba con otra palabra, o con las cifras de su cédula o de su teléfono.",
  "limit": "Se muestran los primeros {count}. Usa el buscador para encontrar los demás.",
  "col.name": "Cliente",
  "col.doc": "Cédula o RIF",
  "col.phone": "Teléfono",
  "inactive": "Archivado",
  "purchases": "Ver compras",
  "purchases.label": "Ver las compras de {name}",

  "editor.new": "Nuevo cliente",
  "editor.edit": "Editar cliente",
  "name": "Nombre o razón social",
  "name.placeholder": "Ej.: María Pérez",
  "name.required": "Escribe el nombre del cliente.",
  "doc": "Cédula o RIF (opcional)",
  "doc.placeholder": "V-12345678 o J-12345678-9",
  "doc.hint": "Escríbelo como quieras: Ventamas le da el formato.",
  "doc.check": "El último dígito no coincide con ese RIF. Revísalo; si está bien así, puedes guardarlo igual.",
  "phone": "Teléfono (opcional)",
  "phone.placeholder": "0414 555 12 34",
  "email": "Correo (opcional)",
  "address": "Dirección (opcional)",
  "address.hint": "Va en la factura.",
  "note": "Nota (opcional)",
  "save": "Guardar",
  "cancel": "Cancelar",
  "archive": "Archivar",
  "restore": "Recuperar",
  "archived.note": "Este cliente está archivado: no aparece al vender.",

  "picker.title": "Cliente de la venta",
  "picker.search": "Buscar cliente",
  "picker.placeholder": "Nombre, cédula o teléfono",
  "picker.none": "Nadie coincide con «{query}».",
  "picker.empty": "Escribe para buscar, o crea un cliente nuevo.",
  "picker.create": "Crear cliente nuevo",
  "picker.create.named": "Crear «{name}»",
  "picker.remove": "Vender sin cliente",
} as const;

export const t = createT(es);
