import { createT } from "../../../renderer/src/i18n";

const es = {
  "nav": "Facturas",
  "settings.label": "Facturación",
  "settings.title": "Facturación",
  "settings.lead":
    "En Venezuela un programa no convierte un documento en factura por sí solo. Una factura es válida si sale de una máquina fiscal, de un talonario o forma libre de una imprenta autorizada por el SENIAT, o de una imprenta digital autorizada. Ventamas te ayuda con dos de esos caminos; el recibo que imprime al vender no es una factura.",
  "settings.review": "Normas revisadas en octubre de 2026 (Providencias SNAT/2011/00071 y SNAT/2018/0141). Las reglas cambian: confirma tu caso con un contador.",
  "mode": "¿Cómo factura tu tienda?",
  "mode.off": "No uso Ventamas para facturar",
  "mode.off.hint": "Ventamas solo imprime su recibo no fiscal.",
  "mode.externa": "Facturo por otro medio y anoto el número",
  "mode.externa.hint": "Para quien usa máquina fiscal, talonario o imprenta digital: en cada venta anotas el número de la factura que emitiste, y queda todo junto.",
  "mode.forma-libre": "Imprimo mis facturas en formas libres",
  "mode.forma-libre.hint": "Ventamas numera la factura y la imprime sobre las hojas con número de control que te hizo una imprenta autorizada.",

  "fiscal.title": "Antes de usar formas libres, comprueba que puedes",
  "fiscal.body": "La ley obliga a facturar solo con máquina fiscal a quien cumple estas tres condiciones a la vez:",
  "fiscal.1": "La mayoría de sus ventas son a personas que no usan la factura para sus impuestos (consumidores finales).",
  "fiscal.2": "Vende más de 1.500 unidades tributarias al año, o el negocio es nuevo.",
  "fiscal.3": "Su actividad está en la lista de la providencia. Entre otras: ropa, calzado y artículos de cuero; belleza y estética; lavado de carros; estacionamientos; fotocopias e impresiones; comidas y bebidas (estas, vendan lo que vendan).",
  "fiscal.result": "Si es tu caso, no uses este modo: factura con tu máquina fiscal y elige «Facturo por otro medio y anoto el número».",

  "issuer.title": "Datos de tu tienda en la factura",
  "issuer.missing": "Falta {what}.",
  "issuer.ok": "{name} · {taxId} · {address}",
  "issuer.edit": "Se cambian en la pestaña Tienda.",
  "regime": "Tipo de contribuyente",
  "regime.ordinario": "Ordinario",
  "regime.ordinario.hint": "Cobras IVA: la factura muestra la base y el impuesto de cada tasa.",
  "regime.formal": "Formal",
  "regime.formal.hint": "Solo vendes productos exentos: la factura no desglosa IVA y lleva la leyenda «Contribuyente Formal».",
  "regime.tax.off": "Para facturar como contribuyente ordinario activa primero el desglose de impuestos, en la pestaña Impuestos.",

  "numbering.title": "Numeración",
  "series": "Serie (opcional)",
  "series.hint": "Solo si tienes varios puntos de emisión. Hasta 4 letras o números.",
  "start": "Primera factura",
  "start.hint": "El número con que empieza Ventamas. Después sigue sola, sin saltos.",
  "start.invalid": "Escribe un número entero mayor que cero.",
  "next": "La próxima factura será la {number}.",

  "paper.title": "Papel",
  "paper": "Tamaño de la forma",
  "paper.carta": "Carta",
  "paper.media-carta": "Media carta",
  "top": "Espacio del encabezado preimpreso (mm)",
  "top.hint": "Lo que mide, desde el borde de arriba, la franja que ya viene impresa. Ventamas empieza a escribir debajo.",
  "top.invalid": "Escribe un número entre 0 y 120.",
  "header": "Imprimir también el nombre, el RIF y la dirección de mi tienda",
  "header.hint": "Actívalo solo si tus formas no los traen impresos.",

  "lot.title": "Formas libres",
  "lot.none": "Todavía no hay un lote registrado. Anota aquí el rango de números de control de la caja de formas que te entregó la imprenta.",
  "lot.current": "Lote en uso: del {first} al {last}{printer}",
  "lot.printer": " · {name}",
  "lot.next": "Próxima hoja: {control}. Quedan {count}.",
  "lot.exhausted": "Este lote se agotó. Registra el siguiente.",
  "lot.new": "Registrar un lote",
  "lot.prefix": "Identificador",
  "lot.prefix.hint": "Las cifras antes del guion: 00",
  "lot.first": "Primer número de control",
  "lot.last": "Último número de control",
  "lot.name": "Imprenta (opcional)",
  "lot.invalid": "Escribe el primer y el último número de control como números enteros.",
  "lot.save": "Registrar lote",
  "lot.saved": "Lote registrado.",
  "save": "Guardar",
  "saved": "Guardado",

  "box.title": "Factura",
  "box.issued": "Factura {number}",
  "box.control": "Control {control}",
  "box.external": "emitida por otro medio",
  "box.issue": "Emitir factura",
  "box.record": "Anotar la factura de esta venta",
  "box.print": "Imprimir en la forma",
  "box.pdf": "Guardar copia",
  "box.void": "Anular",
  "box.saved": "Copia guardada en {file}",
  "box.show": "Mostrar en la carpeta",

  "issue.title": "Emitir factura",
  "issue.number": "Será la factura {number}.",
  "issue.customer": "Datos del cliente",
  "issue.name": "Nombre o razón social",
  "issue.doc": "Cédula o RIF",
  "issue.doc.check": "El último dígito no coincide con ese RIF. Revísalo antes de emitir.",
  "issue.address": "Dirección (opcional)",
  "issue.phone": "Teléfono (opcional)",
  "issue.control": "Número de control de la hoja",
  "issue.control.hint": "Compruébalo con la hoja que está en la impresora: es el que trae impreso.",
  "issue.required.name": "Escribe el nombre o la razón social.",
  "issue.required.doc": "Escribe la cédula o el RIF.",
  "issue.required.control": "Escribe el número de control de la hoja.",
  "issue.missing": "Antes de facturar falta {what}. Se configura en Ajustes › Facturación.",
  "issue.long": "Esta venta tiene {count} líneas y puede no caber en una sola hoja. Una factura no puede ocupar dos.",
  "issue.final": "Una factura emitida no se edita: si hay un error, se anula y se emite otra en una hoja nueva. Después de emitirla, imprímela en su hoja.",
  "issue.confirm": "Emitir factura",
  "cancel": "Cancelar",

  "record.title": "Anotar factura",
  "record.lead": "Anota la factura que emitiste para esta venta con tu máquina fiscal, tu talonario o tu imprenta digital.",
  "record.number": "Número de la factura",
  "record.control": "Número de control o registro de la máquina (opcional)",
  "record.date": "Fecha de la factura",
  "record.required": "Escribe el número de la factura.",
  "record.confirm": "Anotar",

  "void.title": "Anular la factura {number}",
  "void.body": "La factura queda anulada y la venta sigue en pie: podrás facturarla de nuevo. Guarda la hoja anulada con todas sus copias.",
  "void.body.externa": "Se quita la anotación de esta venta. La factura que emitiste por otro medio no cambia.",
  "void.reason": "Motivo",
  "void.reason.placeholder": "Ej.: RIF del cliente mal escrito",
  "void.reason.required": "Escribe el motivo.",
  "void.confirm": "Anular factura",

  "sheet.title": "Anular una hoja",
  "sheet.lead": "Para una hoja que se dañó o se imprimió mal antes de ser factura. Su número de control queda inutilizado.",
  "sheet.control": "Número de control de la hoja",
  "sheet.confirm": "Anular hoja",
  "sheet.action": "Anular una hoja dañada",

  "screen.title": "Facturas",
  "screen.lead": "Auxiliar para armar el Libro de Ventas: las facturas del mes con sus montos en bolívares, a la tasa de cada venta. No es el libro oficial.",
  "screen.month": "Mes",
  "screen.export": "Exportar a hoja de cálculo",
  "screen.exported": "Guardado en {file}",
  "screen.empty.title": "No hay facturas en este mes",
  "screen.empty.body": "Las facturas aparecen aquí al emitirlas o anotarlas desde una venta.",
  "col.date": "Fecha",
  "col.number": "Factura",
  "col.customer": "Cliente",
  "col.exempt": "Exento",
  "col.base": "Base",
  "col.tax": "Impuesto",
  "col.total": "Total",
  "col.status": "Estado",
  "status.void": "Anulada",
  "status.external": "Otro medio",
  "status.issued": "Emitida",
  "totals": "Totales del mes",
  "sheets.title": "Hojas anuladas",
  "open": "Ver la venta de la factura {number}",

  "doc.title": "FACTURA",
  "doc.number": "N.º",
  "doc.date": "Fecha de emisión",
  "doc.rif": "RIF",
  "doc.customer": "Nombre o razón social",
  "doc.customer.doc": "RIF / C.I.",
  "doc.customer.address": "Domicilio",
  "doc.customer.phone": "Teléfono",
  "doc.qty": "Cant.",
  "doc.description": "Descripción",
  "doc.amount": "Monto",
  "doc.discounts": "Descuentos ya aplicados en los montos",
  "doc.base": "Base imponible ({rate})",
  "doc.tax": "{name} ({rate})",
  "doc.exempt": "Exento (E)",
  "doc.total": "TOTAL",
  "doc.rate": "Tipo de cambio del día: {rate}. Equivalente:",
  "doc.formal": "Contribuyente Formal",
  "doc.paid": "Forma de pago",
  "doc.sale": "Venta {number}",
  "doc.copy": "COPIA DE ARCHIVO · SIN VALIDEZ FISCAL",
  "doc.copy.note": "La factura es la forma libre impresa con el número de control {control}.",
} as const;

export const t = createT(es);
