import { createT } from "../../../renderer/src/i18n";

const es = {
  "nav": "Vender",
  "title": "Vender",

  "gate.rates.title": "Confirma la tasa de hoy",
  "gate.rates.body": "Con ella se convierte cada cobro. Parte de la última tasa: confírmala, corrígela o trae la oficial.",
  "gate.cash.title": "La caja está cerrada",
  "gate.cash.body": "Abre la caja con el efectivo que hay en la gaveta y vuelve aquí para vender.",
  "gate.cash.action": "Abrir caja",

  "search.label": "Buscar producto",
  "search.placeholder": "Busca o escanea un producto",
  "search.none": "Ningún producto coincide con «{query}».",
  "search.stock": "{count} en existencia",
  "search.nostock": "Sin existencias",

  "picker.title": "¿Cuál se lleva?",
  "picker.stock": "Hay {count}",
  "picker.nostock": "Sin existencias",

  "cart.empty.title": "La venta está vacía",
  "cart.empty.body": "Busca el primer producto por su nombre o escanea su código de barras.",
  "cart.empty.products": "Ir a Productos",
  "cart.col.product": "Producto",
  "cart.col.qty": "Cantidad",
  "cart.col.price": "Precio",
  "cart.col.total": "Total",
  "cart.less": "Quitar una pieza de {item}",
  "cart.more": "Añadir una pieza de {item}",
  "cart.remove": "Quitar {item} de la venta",
  "cart.over": "Solo hay {count}",
  "cart.none": "Sin existencias",
  "cart.clear": "Vaciar venta",
  "sessionSales": "Ventas de esta caja",

  "total": "Total",
  "pay.title": "Cobrar con",
  "pay.due": "Falta",
  "pay.paid": "Cobrado",
  "pay.remove": "Quitar el pago de {method}",
  "change.title": "Vuelto",
  "change.give": "Dar el vuelto en",
  "change.pending": "Falta entregar",
  "change.over": "El vuelto supera lo que corresponde en {amount}",
  "change.remove": "Quitar el vuelto en {method}",
  "entry.amount": "Monto en {method}",
  "entry.amount.invalid": "Escribe un monto mayor que cero.",
  "entry.note": "Referencia (opcional)",
  "entry.note.placeholder": "Últimos dígitos",
  "entry.add": "Agregar",
  "entry.cancel": "Cancelar",
  "charge": "Cobrar",
  "charge.total": "Cobrar {total}",
  "shortcuts": "buscar · cobro · cobrar",

  "done.title": "Venta registrada",
  "sale.title": "Venta {number}",
  "sale.change": "Vuelto",
  "sale.print": "Imprimir recibo",
  "sale.pdf": "Guardar PDF",
  "sale.saved": "Guardado en {file}",
  "sale.show": "Mostrar en la carpeta",
  "sale.new": "Nueva venta",
  "sale.close": "Cerrar",

  "list.title": "Ventas de esta caja",
  "list.empty": "Todavía no hay ventas en esta caja.",
  "list.col.number": "Venta",
  "list.col.time": "Hora",
  "list.col.pieces": "Piezas",
  "list.col.total": "Total",
  "list.view": "Ver",

  "receipt.tag": "RECIBO · NO FISCAL",
  "receipt.total": "TOTAL",
  "receipt.paid": "Pagos",
  "receipt.change": "Vuelto",
  "receipt.rate": "Tasa del día",
  "receipt.ref": "ref. {note}",
  "receipt.thanks": "¡Gracias por tu compra!",
  "receipt.notice": "Este recibo no es una factura.",

  "settings.title": "Recibos",
  "settings.printer": "Impresora de recibos",
  "settings.printer.ask": "Preguntar cada vez",
  "settings.printer.hint": "Con una impresora elegida, el recibo sale directo, sin preguntar.",
  "settings.printer.missing": "{name} (no conectada)",
  "settings.width": "Ancho del papel",
  "settings.width.80": "80 mm",
  "settings.width.58": "58 mm",
  "settings.test": "Imprimir prueba",
  "settings.test.title": "Prueba de impresión",
  "settings.test.body": "Si lees esto completo y centrado, la impresora y el ancho del papel están bien.",
} as const;

export const t = createT(es);
