import { createT } from "../../../renderer/src/i18n";

const es = {
  "nav": "Vender",
  "title": "Vender",

  "gate.rates.title": "Confirma la tasa de hoy",
  "gate.rates.body": "Con ella se convierte cada cobro. Parte de la última tasa: confírmala, corrígela o trae la oficial.",
  "gate.cash.title": "La caja está cerrada",
  "gate.cash.body": "Abre la caja con el efectivo que hay en la gaveta y vuelve aquí para vender.",
  "gate.cash.action": "Abrir caja",

  "search.label": "Buscar producto",
  "search.placeholder": "Busca o escanea un producto",
  "search.none": "Ningún producto coincide con «{query}».",
  "search.stock": "{count} en existencia",
  "search.nostock": "Sin existencias",
  "search.service": "Servicio",
  "price.from": "desde {price}",
  "price.open": "Precio al cobrar",

  "browse.title": "Productos",
  "browse.all": "Todos",
  "browse.more": "Hay más productos: usa el buscador para encontrarlos.",
  "browse.empty.title": "Todavía no hay productos",
  "browse.empty.body": "Crea el primero y aparecerá aquí, listo para venderlo con un toque.",
  "browse.empty.action": "Ir a Productos",
  "browse.category.empty": "Esta categoría no tiene productos en venta.",

  "picker.title": "¿Cuál se lleva?",
  "picker.title.service": "¿Cuál?",
  "picker.stock": "Hay {count}",
  "picker.nostock": "Sin existencias",

  "open.title": "Precio de {item}",
  "open.label": "Precio",
  "open.invalid": "Escribe el precio como un número mayor que cero.",
  "open.add": "Añadir a la venta",

  "cart.col.product": "Producto",
  "cart.col.qty": "Cantidad",
  "cart.col.total": "Total",
  "cart.each": "{price} c/u",
  "cart.qty": "Cantidad de {item}",
  "cart.less": "Quitar una pieza de {item}",
  "cart.more": "Añadir una pieza de {item}",
  "cart.remove": "Quitar {item} de la venta",
  "cart.edit": "Precio y descuento de {item}",
  "cart.over": "Solo hay {count}",
  "cart.none": "Sin existencias",
  "cart.discount": "Descuento −{amount}",
  "cart.clear": "Vaciar venta",
  "cart.clear.title": "¿Vaciar la venta?",
  "cart.clear.body": "Se quitan sus {count} líneas, los pagos y el descuento. No se puede deshacer.",
  "cart.clear.confirm": "Vaciar",
  "cart.removed": "Quitaste {item}.",
  "cart.undo": "Deshacer",
  "sessionSales": "Ventas de esta caja",

  "line.title": "{item}",
  "line.price": "Precio",
  "line.discount": "Descuento en esta línea",
  "line.discount.kind": "Tipo de descuento",
  "line.discount.percent": "Porcentaje",
  "line.discount.amount": "Monto",
  "line.discount.value.percent": "Porcentaje de descuento",
  "line.discount.value.amount": "Monto de descuento, sobre toda la línea",
  "line.discount.invalid.percent": "Escribe un porcentaje entre 0 y 100.",
  "line.discount.invalid.amount": "Escribe un monto que no pase del precio de la línea.",
  "line.result": "La línea queda en {total}",
  "line.apply": "Aplicar",
  "line.clear": "Quitar descuento",

  "customer": "Cliente",
  "customer.none": "Sin cliente",
  "customer.add": "Poner cliente",
  "customer.change": "Cambiar el cliente: {name}",
  "customer.remove": "Quitar el cliente de la venta",

  "discount": "Descuento",
  "discount.add": "Descuento a la venta",
  "discount.title": "Descuento a toda la venta",
  "discount.hint": "Se aplica después de los descuentos de cada línea y se reparte entre ellas.",
  "discount.value.percent": "Porcentaje de descuento",
  "discount.value.amount": "Monto de descuento",
  "discount.invalid.amount": "Escribe un monto que no pase del total de la venta.",
  "discount.result": "La venta queda en {total}",
  "discount.percent": "Descuento ({percent} %)",
  "discount.lines": "Descuentos por línea",
  "discount.remove": "Quitar el descuento de la venta",

  "note": "Nota",
  "note.add": "Añadir nota",
  "note.title": "Nota de la venta",
  "note.label": "Nota (sale en el recibo)",
  "note.placeholder": "Ej.: Cambio permitido hasta el sábado",
  "note.save": "Guardar",
  "note.remove": "Quitar la nota",

  "park": "Dejar en espera",
  "park.title": "Dejar la venta en espera",
  "park.body": "Queda guardada y puedes atender a otra persona. Para retomarla, toca «En espera».",
  "park.label": "Nombre para reconocerla (opcional)",
  "park.label.placeholder": "Ej.: Señora del vestido azul",
  "park.confirm": "Dejar en espera",
  "parked": "En espera ({count})",
  "parked.title": "Ventas en espera",
  "parked.empty": "No hay ventas en espera.",
  "parked.unnamed": "Venta sin nombre",
  "parked.pieces.one": "1 pieza",
  "parked.pieces": "{count} piezas",
  "parked.take": "Retomar",
  "parked.take.label": "Retomar {name}",
  "parked.discard": "Descartar",
  "parked.discard.label": "Descartar {name}",
  "parked.busy": "Termina o deja en espera la venta actual antes de retomar otra.",
  "parked.dropped.one": "Un producto de esa venta ya no se vende y quedó fuera.",
  "parked.dropped": "{count} productos de esa venta ya no se venden y quedaron fuera.",

  "subtotal": "Subtotal",
  "total": "Total",
  "tax.base": "Base {name}",
  "tax.amount": "{name} {rate}",
  "tax.included": "incluido",
  "tax.exempt": "Exento",
  "pay.title": "Cobrar con",
  "pay.due": "Falta",
  "pay.paid": "Cobrado",
  "pay.remove": "Quitar el pago de {method}",
  "change.title": "Vuelto",
  "change.give": "Dar el vuelto en",
  "change.pending": "Falta entregar",
  "change.over": "El vuelto supera lo que corresponde en {amount}",
  "change.remove": "Quitar el vuelto en {method}",
  "entry.amount": "Monto en {method}",
  "entry.amount.invalid": "Escribe un monto mayor que cero.",
  "entry.quick": "Montos habituales",
  "entry.exact": "Exacto",
  "entry.note": "Referencia (opcional)",
  "entry.note.placeholder": "Últimos dígitos",
  "entry.add": "Agregar",
  "entry.cancel": "Cancelar",
  "charge": "Cobrar",
  "charge.total": "Cobrar {total}",
  "shortcut.search": "buscar",
  "shortcut.pay": "cobro",
  "shortcut.customer": "cliente",
  "shortcut.discount": "descuento",
  "shortcut.park": "espera",
  "shortcut.charge": "cobrar",

  "done.title": "Venta registrada",
  "sale.title": "Venta {number}",
  "sale.change": "Vuelto",
  "sale.customer": "Cliente",
  "sale.print": "Imprimir recibo",
  "sale.pdf": "Guardar PDF",
  "sale.saved": "Guardado en {file}",
  "sale.show": "Mostrar en la carpeta",
  "sale.new": "Nueva venta",
  "sale.close": "Cerrar",

  "list.title": "Ventas de esta caja",
  "list.empty": "Todavía no hay ventas en esta caja.",
  "list.col.number": "Venta",
  "list.col.time": "Hora",
  "list.col.date": "Fecha",
  "list.col.customer": "Cliente",
  "list.col.pieces": "Piezas",
  "list.col.total": "Total",
  "list.view": "Ver",
  "list.view.label": "Ver la venta {number}",

  "history.nav": "Ventas",
  "history.title": "Ventas",
  "history.search": "Buscar por número de venta o cliente",
  "history.period": "Periodo",
  "history.period.today": "Hoy",
  "history.period.week": "7 días",
  "history.period.month": "Este mes",
  "history.period.all": "Todo",
  "history.customer": "Compras de {name}",
  "history.customer.clear": "Ver las ventas de todos",
  "history.empty.title": "No hay ventas en este periodo",
  "history.empty.body": "Prueba con otro periodo o quita la búsqueda.",
  "history.none.title": "Todavía no hay ventas",
  "history.none.body": "Cuando cobres la primera, aparecerá aquí con su recibo.",
  "history.count.one": "1 venta",
  "history.count": "{count} ventas",
  "history.sold": "Vendido",
  "history.limit": "Se muestran las {count} más recientes. Acota el periodo para ver las demás.",

  "receipt.tag": "RECIBO · NO FISCAL",
  "receipt.customer": "Cliente",
  "receipt.subtotal": "Subtotal",
  "receipt.discount": "Descuento",
  "receipt.total": "TOTAL",
  "receipt.paid": "Pagos",
  "receipt.change": "Vuelto",
  "receipt.rate": "Tasa del día",
  "receipt.ref": "ref. {note}",
  "receipt.thanks": "¡Gracias por tu compra!",
  "receipt.notice": "Este recibo no es una factura.",

  "settings.title": "Recibos",
  "settings.printer": "Impresora de recibos",
  "settings.printer.ask": "Preguntar cada vez",
  "settings.printer.hint": "Con una impresora elegida, el recibo sale directo, sin preguntar.",
  "settings.printer.missing": "{name} (no conectada)",
  "settings.width": "Ancho del papel",
  "settings.width.80": "80 mm",
  "settings.width.58": "58 mm",
  "settings.test": "Imprimir prueba",
  "settings.test.title": "Prueba de impresión",
  "settings.test.body": "Si lees esto completo y centrado, la impresora y el ancho del papel están bien.",
} as const;

export const t = createT(es);
