import { createT } from "../../../renderer/src/i18n";

const es = {
  "nav": "Caja",
  "title": "Caja",

  "closed.title": "La caja está cerrada",
  "closed.lead": "Para vender, abre la caja con el efectivo que hay en la gaveta en este momento.",
  "open.float": "Fondo inicial",
  "open.float.hint": "Lo que hay ahora en la gaveta para dar vuelto. Deja en blanco lo que no tengas.",
  "open.invalid": "Escribe los montos como números, por ejemplo 20 o 20,50.",
  "open.action": "Abrir caja",

  "opened.since": "Abierta desde {when}",
  "stat.sales": "Ventas",
  "stat.total": "Vendido",
  "stat.none": "Aún no hay ventas",
  "by.method": "Dinero por medio de pago",
  "col.method": "Medio de pago",
  "col.opening": "Fondo",
  "col.sales": "Cobrado",
  "col.change": "Vuelto",
  "col.moves": "Entradas y salidas",
  "col.expected": "Debe haber",
  "col.counted": "Contado",
  "col.difference": "Diferencia",
  "move.action": "Entrada o salida de efectivo",
  "close.action": "Cerrar caja",

  "move.title": "Entrada o salida de efectivo",
  "move.kind": "¿Qué pasó?",
  "move.out": "Salió dinero",
  "move.in": "Entró dinero",
  "move.method": "De dónde",
  "move.amount": "Monto",
  "move.amount.invalid": "Escribe un monto mayor que cero.",
  "move.reason": "Motivo",
  "move.reason.placeholder": "Ej.: pago del almuerzo, retiro del dueño",
  "move.reason.required": "Escribe el motivo.",
  "move.save": "Registrar",
  "cancel": "Cancelar",

  "close.title": "Cerrar caja",
  "close.lead": "Cuenta lo que hay de cada medio y escríbelo. Ventamas lo compara con lo que debería haber.",
  "close.counted.label": "Contado en {method}",
  "close.invalid": "Escribe lo contado de cada medio que tuvo movimiento.",
  "close.note": "Nota (opcional)",
  "close.note.placeholder": "Ej.: faltó un dólar de vuelto",
  "close.confirm": "Cerrar caja",
  "close.match": "Cuadra",
  "close.over": "Sobra",
  "close.short": "Falta",

  "report.title": "Cierre de caja",
  "report.opened": "Abierta",
  "report.closed": "Cerrada",
  "report.print": "Imprimir cierre",
  "report.pdf": "Guardar PDF",
  "report.saved": "Guardado en {file}",
  "report.show": "Mostrar en la carpeta",
  "report.done": "Listo",
  "report.note": "Nota",
  "report.nonfiscal": "CIERRE DE CAJA",

  "history": "Cajas anteriores",
  "history.empty": "Aquí aparecerá cada caja que cierres.",
  "history.open": "Abierta",
  "history.view": "Ver cierre",

  "settings.title": "Medios de pago",
  "settings.hint": "Desactiva los que tu tienda no usa: dejarán de aparecer al cobrar.",
  "kind.efectivo": "Efectivo",
  "kind.electronico": "Electrónico",
} as const;

export const t = createT(es);
