import { createT } from "../../../renderer/src/i18n";

const es = {
  "nav": "Caja",
  "title": "Caja",

  "closed.title": "La caja está cerrada",
  "closed.lead": "Para vender, abre la caja con el efectivo que hay en la gaveta en este momento.",
  "open.float": "Fondo inicial",
  "open.float.hint": "Lo que hay ahora en la gaveta para dar vuelto. Deja en blanco lo que no tengas.",
  "open.invalid": "Escribe los montos como números, por ejemplo 20 o 20,50.",
  "open.action": "Abrir caja",

  "opened.since": "Abierta desde {when}",
  "stat.sales": "Ventas",
  "stat.total": "Vendido",
  "stat.none": "Aún no hay ventas",
  "by.method": "Dinero por medio de pago",
  "col.method": "Medio de pago",
  "col.opening": "Fondo",
  "col.sales": "Cobrado",
  "col.change": "Vuelto",
  "col.moves": "Entradas y salidas",
  "col.expected": "Debe haber",
  "col.counted": "Contado",
  "col.difference": "Diferencia",
  "move.action": "Entrada o salida de efectivo",
  "close.action": "Cerrar caja",
  "cut.action": "Corte de caja",

  "move.title": "Entrada o salida de efectivo",
  "move.kind": "¿Qué pasó?",
  "move.out": "Salió dinero",
  "move.in": "Entró dinero",
  "move.method": "De dónde",
  "move.amount": "Monto",
  "move.amount.invalid": "Escribe un monto mayor que cero.",
  "move.reason": "Motivo",
  "move.reason.placeholder": "Ej.: pago del almuerzo, retiro del dueño",
  "move.reason.required": "Escribe el motivo.",
  "move.reason.quick": "Motivos habituales",
  "move.reason.out.1": "Retiro a resguardo",
  "move.reason.out.2": "Pago a proveedor",
  "move.reason.out.3": "Gasto del local",
  "move.reason.out.4": "Cambio de billetes",
  "move.reason.in.1": "Aporte de fondo",
  "move.reason.in.2": "Cambio de billetes",
  "move.reason.in.3": "Cobro de una deuda",
  "move.save": "Registrar",
  "cancel": "Cancelar",

  "close.title": "Cerrar caja",
  "close.lead": "Cuenta lo que hay de cada medio y escríbelo. Ventamas lo compara con lo que debería haber.",
  "close.lead.blind": "Cuenta lo que hay de cada medio y escríbelo; donde no haya nada, escribe 0. Verás la diferencia al cerrar.",
  "close.counted.label": "Contado en {method}",
  "close.invalid.blind": "Escribe lo contado de cada medio. Donde no haya nada, escribe 0.",
  "close.bills": "Contar billetes",
  "close.bills.label": "Contar billetes de {method}",
  "bills.title": "Contar {method}",
  "bills.lead": "Escribe cuántos billetes hay de cada uno. Ventamas hace la suma.",
  "bills.col.bill": "Billete",
  "bills.col.qty": "Cuántos hay",
  "bills.col.sum": "Suma",
  "bills.qty.label": "Billetes de {bill}",
  "bills.loose": "Monedas y lo demás",
  "bills.total": "Total contado",
  "bills.invalid": "Escribe cantidades enteras y montos válidos.",
  "bills.apply": "Usar este total",
  "close.invalid": "Escribe lo contado de cada medio que tuvo movimiento.",
  "close.note": "Nota (opcional)",
  "close.note.placeholder": "Ej.: faltó un dólar de vuelto",
  "close.confirm": "Cerrar caja",
  "close.match": "Cuadra",
  "close.over": "Sobra",
  "close.short": "Falta",

  "report.title": "Cierre de caja",
  "report.title.cut": "Corte de caja",
  "report.cut.note": "La caja sigue abierta: esto es lo que lleva hasta ahora.",
  "report.print.cut": "Imprimir corte",
  "report.nonfiscal.cut": "CORTE DE CAJA · PARCIAL",
  "report.at": "Corte hecho",
  "report.opened": "Abierta",
  "report.closed": "Cerrada",
  "report.print": "Imprimir cierre",
  "report.pdf": "Guardar PDF",
  "report.saved": "Guardado en {file}",
  "report.show": "Mostrar en la carpeta",
  "report.done": "Listo",
  "report.note": "Nota",
  "report.nonfiscal": "CIERRE DE CAJA",

  "history": "Cajas anteriores",
  "history.empty": "Aquí aparecerá cada caja que cierres.",
  "history.open": "Abierta",
  "history.view": "Ver cierre",

  "settings.label": "Caja y pagos",
  "settings.title": "Medios de pago",
  "settings.hint": "Desactiva los que tu tienda no usa: dejarán de aparecer al cobrar.",
  "settings.cash.title": "Cierre de caja",
  "settings.blind": "Contar a ciegas",
  "settings.blind.hint": "Al cerrar la caja no se muestra cuánto debería haber: primero se cuenta y después se ve la diferencia. Así el conteo no se acomoda a lo esperado.",
  "kind.efectivo": "Efectivo",
  "kind.electronico": "Electrónico",
} as const;

export const t = createT(es);
